---
- name: Get installed kernel packages
  package_facts:
    manager: auto
  tags:
    - preload

- name: Install required kernel version
  yum:
    name: kernel-{{ kernel_version }}
    state: present
  tags:
    - preload

- name: Remove all other kernels
  yum:
    name: "{{ item }}"
    state: absent
  with_items: "{{ ansible_facts.packages | dict2items | selectattr('key', 'search', '^kernel-[0-9]') | map(attribute='key') | list }}"
  tags:
    - preload

- name: Add linstor repo
  yum_repository:
    name: drbd
    description: LINBIT Packages for LINSTOR and DRBD
    baseurl: "{{ linbit_repo_baseurl }}/yum/rhel{{ rhel_major_version }}/drbd-9/x86_64"
    gpgcheck: true
    gpgkey: https://packages.linbit.com/package-signing-pubkey.asc
  tags:
    - preload

# cat /etc/os-release | curl -sT - -X POST https://bestmodule.drbd.io/api/v1/best/$(uname -r)
- name: Determine best kmod
  uri:
    url: https://bestmodule.drbd.io/api/v1/best/{{ kernel_version }}
    src: "/etc/os-release"
    remote_src: "True"
    method: POST
    body_format: raw
    return_content: true
  register: best_kmod
  tags:
    - preload

- debug:
    var: best_kmod.content
  tags:
    - preload

- name: Install DRBD
  yum:
    pkg:
      - drbd-utils
      - "{{ best_kmod.content | regex_replace('(.*)\\.rpm', '\\1') }}"
  notify:
    - Restart satellite
  tags:
    - preload

- name: Configure DRBD utils to not phone home
  lineinfile:
    path: /etc/drbd.d/global_common.conf
    regexp: 'usage-count'
    line: "\tusage-count no;"
    state: present
    validate: drbdadm -c %s dump
  tags:
    - preload

- name: Install software components
  yum:
    pkg:
      - gnupg
      - lvm2
      - linstor-controller
      - linstor-satellite
      - linstor-client
  notify:
    - Restart satellite
  tags:
    - preload

- name: Trigger handlers
  meta: flush_handlers

- name: Add blacklist for DRBD devices
  copy:
    src: lvm.conf
    dest: /etc/lvm/lvm.conf
    owner: root
    mode: 0644
  notify:
    - Restart satellite
  tags:
    - preload

- name: Populate service facts
  service_facts:
  tags:
    - preload


- name: Stop multipathd, as it could screw with DRBD
  service:
    name: multipathd
    state: stopped
    enabled: no
  when: '"multipathd.service" in services'
  tags:
    - preload

- name: Restart systemd-udevd to ensure the hostname got updated
  service:
    name: systemd-udevd
    state: restarted
  tags:
    - preload

- name: Configure satellite
  copy:
    src: linstor_satellite.toml
    dest: /etc/linstor/linstor_satellite.toml
    owner: root
    mode: 0644
  notify:
    - Restart satellite
  tags:
    - preload

- name: Enable satellite
  service:
    name: linstor-satellite
    enabled: yes
  notify:
    - Restart satellite
  tags:
    - preload

- name: Set up linstor-controller service (on controller)
  service:
    name: linstor-controller
    enabled: yes
    state: started
  when: inventory_hostname in linstor_controller_hosts
  tags:
    - run

- name: Wait for controller to come online
  wait_for:
    port: 3370
  when: inventory_hostname in linstor_controller_hosts
  tags:
    - run

- name: Disable linstor-controller service (on non-controllers)
  service:
    name: linstor-controller
    enabled: no
    state: stopped
  when: inventory_hostname not in linstor_controller_hosts
  tags:
    - run

- name: Create linstor configuration file
  template:
    src: linstor-client.conf.j2
    dest: /etc/linstor/linstor-client.conf
  tags:
    - run
