[values]
LinstorGatewayVersion = "*"

[[steps]]
[steps.docker]
image = "quay.io/ansible/ansible-runner:stable-2.9-devel"
command = [
    "ansible-playbook",
    "--inventory", "/virter/workspace/virter/inventory",
    "/virter/workspace/virter/provision-playbook.yml",
    "--extra-vars", "linstor_gateway_version={{ .LinstorGatewayVersion }}",
    "--tags", "testimage"
]
[steps.docker.env]
ANSIBLE_PIPELINING="yes"
