[values]
DRBDRepoBaseURL = ""
PacemakerRepoBaseURL = ""
CIRepoBaseURL = ""

[[steps]]
[steps.docker]
image = "quay.io/ansible/ansible-runner:stable-2.9-devel"
command = [
    "ansible-playbook",
    "--inventory", "/virter/workspace/virter/inventory",
    "/virter/workspace/virter/provision-playbook.yml",
    "--extra-vars", "drbd_repo_baseurl={{ .DRBDRepoBaseURL }}",
    "--extra-vars", "pacemaker_repo_baseurl={{ .PacemakerRepoBaseURL }}",
    "--extra-vars", "ci_repo_baseurl={{ .CIRepoBaseURL }}",
    "--tags", "preload"
]
[steps.docker.env]
ANSIBLE_PIPELINING="yes"
