version = 1

[values]
LinstorGatewayVersion = "*"

[[steps]]
[steps.container]
image = "quay.io/ansible/awx-ee:24.6.1"
user = "0"
command = [
	"sh", "/virter/workspace/virter/run-ansible-playbook.sh",
	"--inventory", "/virter/workspace/virter/inventory",
	"/virter/workspace/virter/provision-playbook.yml",
	"--extra-vars", "linstor_gateway_version={{ .LinstorGatewayVersion }}",
	"--tags", "testimage"
]
[steps.container.env]
ANSIBLE_PIPELINING = "yes"
