name: Test
on: pull_request

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Build project
        run: |
          make release
      - name: Extract Release Notes
        id: extract_release_notes
        uses: ffurrer2/extract-release-notes@v1.16.0
      - name: Debug
        shell: bash
        run: echo ${{ steps.extract_release_notes.outputs.release_notes }}
